drop table if exists office_table;

create table office_table ( i_office_id integer identity primary key, c_code varchar (100) , c_name varchar (200) ,i_status integer );

insert into office_table (c_code,c_name,i_status) values ('KOP','Shipco Transport Koper',0);
insert into office_table (c_code,c_name,i_status) values ('SJKT','Shipco Transport Indonesia',0);
insert into office_table (c_code,c_name,i_status) values ('CMB','Shipco Transport Lanka Pvt Ltd',0);
insert into office_table (c_code,c_name,i_status) values ('KHI','Shipco Transport Pakistan',0);
insert into office_table (c_code,c_name,i_status) values ('PCHS','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('AUH','SSC Consolidation Abu Dhabi',0);
insert into office_table (c_code,c_name,i_status) values ('CKG','Shipco Transport Shanghai',0);
insert into office_table (c_code,c_name,i_status) values ('BOS','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('RLGB','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('BRC','Bangkok Resource Center',0);
insert into office_table (c_code,c_name,i_status) values ('XMN','Shipco Transport Xiamen',0);
insert into office_table (c_code,c_name,i_status) values ('LYP','Shipco Transport Pakistan',0);
insert into office_table (c_code,c_name,i_status) values ('HAN','Shipco Transport Vietnam',0);
insert into office_table (c_code,c_name,i_status) values ('AKL','Shipco Transport NZ',0);
insert into office_table (c_code,c_name,i_status) values ('TPE','Shipco Transport Taiwan Co.,Ltd.',0);
insert into office_table (c_code,c_name,i_status) values ('CORP','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('LGB','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('CHS','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('NYC','Shipco Transport USA','1');
insert into office_table (c_code,c_name,i_status) values ('ATL','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('SFO','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('ANYC','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('CHI','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('SEA','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('JFK','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('HOU','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('MIA','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('ILGB','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('INYC','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('ALGB','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('RMIA','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('RNYC','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('ACHI','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('ANT','SSC Consolidation',0);
insert into office_table (c_code,c_name,i_status) values ('BKK','Shipco Transport Bangkok',0);
insert into office_table (c_code,c_name,i_status) values ('COL','Shipco Transport Pte Ltd',0);
insert into office_table (c_code,c_name,i_status) values ('CPH','Shipco Transport Copenhagen',0);
insert into office_table (c_code,c_name,i_status) values ('GDY','Shipco Transport Poland',0);
insert into office_table (c_code,c_name,i_status) values ('GOT','Shipco Transport Scandinavia',0);
insert into office_table (c_code,c_name,i_status) values ('HEL','Shipco Transport Scandinavia',0);
insert into office_table (c_code,c_name,i_status) values ('HKG','Shipco Transport Hong Kong',0);
insert into office_table (c_code,c_name,i_status) values ('JKT','Shipco Transport Indonesia',0);
insert into office_table (c_code,c_name,i_status) values ('LDN','Shipco Transport Great Britain',0);
insert into office_table (c_code,c_name,i_status) values ('MNL','Shipco Transport Philippines',0);
insert into office_table (c_code,c_name,i_status) values ('ODA','Shipco Transport Ukraine',0);
insert into office_table (c_code,c_name,i_status) values ('OSL','Shipco Transport Scandinavia',0);
insert into office_table (c_code,c_name,i_status) values ('PEN','Shipco Transport Malaysia',0);
insert into office_table (c_code,c_name,i_status) values ('PKL','Shipco Transport Malaysia',0);
insert into office_table (c_code,c_name,i_status) values ('RIX','Shipco Transport Balticum',0);
insert into office_table (c_code,c_name,i_status) values ('ROT','SSC Consolidation',0);
insert into office_table (c_code,c_name,i_status) values ('SCL','Shipco Transport Santiago',0);
insert into office_table (c_code,c_name,i_status) values ('SHA','Shipco Transport Shanghai',0);
insert into office_table (c_code,c_name,i_status) values ('SIN','Shipco Transport Singapore',0);
insert into office_table (c_code,c_name,i_status) values ('SUB','Shipco Transport Indonesia',0);
insert into office_table (c_code,c_name,i_status) values ('TLL','Shipco Transport Balticum',0);
insert into office_table (c_code,c_name,i_status) values ('TYO','Shipco Transport Tokyo',0);
insert into office_table (c_code,c_name,i_status) values ('VNO','Shipco Transport Balticum',0);
insert into office_table (c_code,c_name,i_status) values ('TOR','Shipco Transport Canada',0);
insert into office_table (c_code,c_name,i_status) values ('MON','Shipco Transport Canada',0);
insert into office_table (c_code,c_name,i_status) values ('HCM','Shipco Transport Vietnam',0);
insert into office_table (c_code,c_name,i_status) values ('SZX','Shipco Transport Shenzen',0);
insert into office_table (c_code,c_name,i_status) values ('DLC','Shipco Transport Dalian',0);
insert into office_table (c_code,c_name,i_status) values ('GZP','Shipco Transport Guangzhou',0);
insert into office_table (c_code,c_name,i_status) values ('STP','Shipco Transport Russia',0);
insert into office_table (c_code,c_name,i_status) values ('HPH','Shipco Transport Vietnam',0);
insert into office_table (c_code,c_name,i_status) values ('ABKK','Shipco Transport Bangkok',0);
insert into office_table (c_code,c_name,i_status) values ('AHOU','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('DUB','Shipco Transport Dublin',0);
insert into office_table (c_code,c_name,i_status) values ('LHE','Shipco Transport Pakistan',0);
insert into office_table (c_code,c_name,i_status) values ('DXB','SSC Consolidation United Arab Emirates',0);
insert into office_table (c_code,c_name,i_status) values ('MOW','Shipco Transport Russia',0);
insert into office_table (c_code,c_name,i_status) values ('ADXB','SSC Consolidation United Arab Emirates',0);
insert into office_table (c_code,c_name,i_status) values ('SKT','Shipco Transport Pakistan',0);
insert into office_table (c_code,c_name,i_status) values ('IEV','Shipco Transport Ukraine',0);
insert into office_table (c_code,c_name,i_status) values ('IST','Shipco Transport Istanbul',0);
insert into office_table (c_code,c_name,i_status) values ('NGB','Shipco Transport Shanghai',0);
insert into office_table (c_code,c_name,i_status) values ('TAO','Shipco Transport Shanghai',0);
insert into office_table (c_code,c_name,i_status) values ('LAX','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('IND','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('MNC','Shipco Transport Great Britain',0);
insert into office_table (c_code,c_name,i_status) values ('LCH','Shipco Transport Bangkok',0);
insert into office_table (c_code,c_name,i_status) values ('DAD','Shipco Transport Vietnam',0);
insert into office_table (c_code,c_name,i_status) values ('PUS','Shipco Transport Korea',0);
insert into office_table (c_code,c_name,i_status) values ('SEL','Shipco Transport Korea',0);
insert into office_table (c_code,c_name,i_status) values ('BUH','Shipco Transport S.R.L.',0);
insert into office_table (c_code,c_name,i_status) values ('PNQ','Shipco-IT Private Limited',0);
insert into office_table (c_code,c_name,i_status) values ('IPH','Shipco Transport Malaysia',0);
insert into office_table (c_code,c_name,i_status) values ('PGU','Shipco Transport Malaysia',0);
insert into office_table (c_code,c_name,i_status) values ('CEB','Shipco Transport Philippines',0);
insert into office_table (c_code,c_name,i_status) values ('IZM','Shipco Transport Istanbul',0);
insert into office_table (c_code,c_name,i_status) values ('QIN','Shipco Transport Qingdao',0);
insert into office_table (c_code,c_name,i_status) values ('NBO','Shipco Transport Ningbo',0);
insert into office_table (c_code,c_name,i_status) values ('SOF','Shipco Transport Bulgaria EOOD',0);
insert into office_table (c_code,c_name,i_status) values ('SHJ','SSC Consolidation Abu Dhabi',0);
insert into office_table (c_code,c_name,i_status) values ('TNYC','Shipco Transport USA',0);
insert into office_table (c_code,c_name,i_status) values ('BOM','Shipco-IT Private Limited',0);



